dubbo:
  application:
    qos-enable: false

  scan:
    base-packages: xyz.vopen.oss.services.auth.service

  config:
    multiple: true
  # protocol
  protocols:
    dubbo:
      name: dubbo
      port: -1

    rest:
      name: rest
      port: 38080

  # registry
  registry:
    address: nacos://127.0.0.1:8848