dubbo:
  application:
    qos-enable: false

  scan:
    base-packages: xyz.vopen.oss.services.auth.service

  # protocol
  protocol:
    name: dubbo
    port: -1
    
  # registry
  registry:
    address: nacos://127.0.0.1:8848