## gateway application
server:
  port: 7777

spring:
  application:
    name: 'OSS-GATEWAY'
  jmx:
    enabled: false
  cloud:
    gateway:
      default-filters:
        - PrefixPath=/httpbin
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar

      routes:
        - id: default_path_to_httpbin
          uri: ${test.uri}
          order: 10000
          predicates:
            - Path=/**

## logger config
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'